project:
  type: website
  output-dir: docs

website:
  title: "Altermap"
  navbar:
    left:
      - href: index.qmd
        text: "En bref"
      - href: equipe.qmd
        text: Equipe
      - text: Groupes de travail
        menu:
          - href: axe1.qmd  
            text: "1. DÃ©coupages du Monde"
          - href: axe2.qmd  
            text: "2. Limites urbain-rural"            
          - href: axe3.qmd  
            text: "3. Changement climatique"
          - href: axe4.qmd  
            text: "4. Maillages territoriaux" 
          - href: axe5.qmd  
            text: "5. Trajectoires de vie"
          - href: axe6.qmd  
            text: "6. Habiter la ville"             
      - posts.qmd
    right: 
      - icon: github # add icons as navbar buttons
        href: https://github.com/worldregio/altermap/
        target: _blank
  page-footer:
    background: dark
    left: Copyright 2026, Claude Grasland
format:
  html:
    theme: 
      light: minty    
      dark: solar
    css: styles.css
    toc: true



